# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run Tests

env:
  TEST_PATH: BSS_Backend_Opgave.Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: cd ${{ env.TEST_PATH }} && dotnet restore
    - name: Build
      run: cd ${{ env.TEST_PATH }} && dotnet build --no-restore
    - name: Run Unit & Integration Tests
      run: cd ${{ env.TEST_PATH }} && dotnet test /p:CollectCoverage=true --no-build
    - name: Upload to CodeCov
      uses: codecov/codecov-action@v5.0.7
      with:
        name: Code Coverage Report
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
